name: terraform CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      TF_VAR_password: ${{ secrets.TF_VAR_password }}
      TF_VAR_subscription_id: ${{ secrets.TF_VAR_subscription_id }}

    defaults:
      run:
        working-directory: ./terraform
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.9

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -var-file=terraform.tfvars --out=tfplan

    - name: Upload tfplan
      uses: actions/upload-artifact@v3
      with:
        name: ./terraform/tfplan
  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: prod
    if : github.event_name == 'workflow_dispatch'
    env:
      TF_VAR_password: ${{ secrets.TF_VAR_password }}
      TF_VAR_subscription_id: ${{ secrets.TF_VAR_subscription_id }}
    defaults:
      run:
        working-directory: ./terraform
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.9
    - name: Terraform Init
      run: terraform init
    - name: Download tfplan
      uses: actions/download-artifact@v3
      with:
        name: tfplan
        path: ./terraform
    - name: Terraform Apply
      run: terraform apply -auto-approve ./terraform/tfplan
